### ISSUE TITLE
Relay mode: control channel selection causes TX collisions

### ISSUE THREAD

**Issue by a-f-G-U-C** [sybip/gtm-lab#3]
In the code section for sending queued transmissions, the **current** control channel is used by default as the control channel for the transmission.
https://github.com/sybip/gtm-lab/blob/f82979c772b9b5e2653856e0b0100707dc698469/gtmRadio.cpp#L680-L682
This is *probably OK* in most cases, when the current control channel is reached as a result of hopping, however, in a relaying scenario, the current control channel is always the control channel of the previously received object. 
This causes all relays to start transmitting at the same time on the same control channel, which **guarantees** a collision rather than avoiding it as intended.
The problem could be mitigated (untested!) by always jumping to a random control channel before transmission.

**Comment by sybip** [comment]
Acknowledged with thanks. There's a pretty serious design flaw in the TX code at the moment.

**Comment by sybip** [comment]
With apologies for the delay, this issue should be fixed in commit https://github.com/sybip/gtm-lab/commit/f947af7eed5aa646646706c6f82a6b30cad31552
