### ISSUE TITLE
peripheral.h missing

### ISSUE THREAD

**Issue by djkazic** [sybip/gtm-lab#4]
I had to comment out the include. Where can I get this file? It seems to be for board-specific functionality.

**Comment by sybip** [comment]
My apologies - peripheral.h is unpublished work in progress that's not fit for release just yet, and the line that includes it should have stayed commented out for now. I have updated the referring file, and thanks for the heads-up.

FYI, the only new functionality that's enabled by that file is battery levels on the TBeam (the only supported board with a power management unit) - fairly inessential at this stage.

**Comment by sybip** [comment]
I have pushed the peripheral support code, which should properly close this issue :)
